// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIsQQ7zUrG24ytSdW_PtjQX1uCZplG_TA',
    appId: '1:119111246639:android:b05bf20e7297f0387c77da',
    messagingSenderId: '119111246639',
    projectId: 'sekolahdulu-5936e',
    databaseURL: 'https://sekolahdulu-5936e-default-rtdb.firebaseio.com',
    storageBucket: 'sekolahdulu-5936e.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6z0wVHk21CgB-ddOMn3cjDl63ueBYiT4',
    appId: '1:119111246639:web:1dfd5c6aa60bdf3d7c77da',
    messagingSenderId: '119111246639',
    projectId: 'sekolahdulu-5936e',
    authDomain: 'sekolahdulu-5936e.firebaseapp.com',
    databaseURL: 'https://sekolahdulu-5936e-default-rtdb.firebaseio.com',
    storageBucket: 'sekolahdulu-5936e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnGwtZy6X7tPX_mjbJIlufNDBph2H7_dA',
    appId: '1:119111246639:ios:4cbaf36f00ae66997c77da',
    messagingSenderId: '119111246639',
    projectId: 'sekolahdulu-5936e',
    databaseURL: 'https://sekolahdulu-5936e-default-rtdb.firebaseio.com',
    storageBucket: 'sekolahdulu-5936e.appspot.com',
    iosBundleId: 'com.example.sekolahdulu',
  );

}